// <auto-generated />
namespace WebsiteBEAT_v0.Migrations.SiteMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Uninitializedlistsfixattempt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Uninitializedlistsfixattempt));
        
        string IMigrationMetadata.Id
        {
            get { return "202009050208005_Uninitialized lists fix attempt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
